/* WarpedFramework 2D - java API - Copyright (C) 2021-2024 Angelo Wilson | released under LGPL 2.1-or-later https://opensource.org/license/lgpl-2-1*/

package warped.application.quest;

public enum QuestStageType {

	//--------
	//----------------Events Triggered by Survey Completion----
	//--------(ORBITAL STAGES)
	//Meteorological Anomaly
	ANOMALY_THUNDERSTORM,
	ANOMALY_LIGHTNINGSTORM,
	ANOMALY_FIRESTORM,
	ANOMALY_ICESTORM,
	ANOMALY_RAINSTORM,
	ANOMALY_WINDSTORM,

	ANOMALY_FLOODING,
	ANOMALY_DROUGHT,
	
	ANOMALY_ALGALBLOOM,
	ANOMALY_TIDAL,
	ANOMALY_KINGTIDE,
	ANOMALY_ROGUEWAVE,
	ANOMALY_RIPCURRENTS,
	ANOMALY_WHIRLPOOLS,
	
	ANOMALY_WILDFIRE,
	ANOMALY_ACIDRAIN,
	ANOMALY_AVALANCH,
	ANOMALY_MUDSLIDE,
	ANOMALY_EROSION,
	ANOMALY_SINKHOLE,
	
	ANOMALY_CYCLONE,
	ANOMALY_TORNADO,
	ANOMALY_SANDSTORM,
	
	//Geological Anomaly
	ANOMALY_GEOTHERMAL,
	ANOMALY_EARTHQUAKE,
	ANOMALY_VOLCANO,
	ANOMALY_SUPERVOLCANO,
	ANOMALY_MAGNETIC,
	
	//Astronomical Anomaly
	ANOMALY_SOLARFLARE,
	ANOMALY_SOLARSTORM,
	ANOMALY_SUPERNOVA,
	ANOMALY_QUAZAR,
	ANOMALY_ROGUEPLANET,
	ANOMALY_ROGUESTAR,
	ANOMALY_ROGUEBLACKHOLE,
	ANOMALY_ROGUEMOON,
	
	//Archeological Anomaly
	ANOMALY_RUINS,
	ANOMALY_ARTIFACT,
	ANOMALY_COINS,
	ANOMALY_TECHNOLOGY,
	ANOMALY_DEBRIS,
		
	//Biological Anomaly
	ANOMALY_FLORA,
	ANOMALY_FAUNA,
	ANOMALY_PHANTASM,
	ANOMALY_CRYATALINELIFE,
	ANOMALY_SHAPESHIFTER,
		
	//Hostile Anomaly 
	ANOMALY_PIRATES,
	ANOMALY_BATTLE,
	
	//Communication Anomaly
	ANOMALY_DISTRESSBEACON,
	ANOMALY_WELCOMBEACON,
	ANOMALY_RADIOFREQUENCY,
	
	
	//--------
	//---------------- 
	//--------(ENTRY STAGES)
	
	
	
	
	
	
	
	
	
	
}
